// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1TTtaJ5JDuCMkXDJUTSQ9nfnn1JS3-BU',
    appId: '1:1004778782264:web:3da611c4e1c406c72030cd',
    messagingSenderId: '1004778782264',
    projectId: 'scamreport-62b4c',
    authDomain: 'scamreport-62b4c.firebaseapp.com',
    storageBucket: 'scamreport-62b4c.firebasestorage.app',
    measurementId: 'G-FH20DFXGHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXYlu6fcbib2OG_Pf3da0wii_ypzQHhFM',
    appId: '1:1004778782264:android:852d4161a7bed2962030cd',
    messagingSenderId: '1004778782264',
    projectId: 'scamreport-62b4c',
    storageBucket: 'scamreport-62b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3nKPSR2PKSBuav6Kd95ZCi6t5rJ1WJIQ',
    appId: '1:1004778782264:ios:333e112037c5fdbf2030cd',
    messagingSenderId: '1004778782264',
    projectId: 'scamreport-62b4c',
    storageBucket: 'scamreport-62b4c.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3nKPSR2PKSBuav6Kd95ZCi6t5rJ1WJIQ',
    appId: '1:1004778782264:ios:333e112037c5fdbf2030cd',
    messagingSenderId: '1004778782264',
    projectId: 'scamreport-62b4c',
    storageBucket: 'scamreport-62b4c.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1TTtaJ5JDuCMkXDJUTSQ9nfnn1JS3-BU',
    appId: '1:1004778782264:web:28f115d63be1eeed2030cd',
    messagingSenderId: '1004778782264',
    projectId: 'scamreport-62b4c',
    authDomain: 'scamreport-62b4c.firebaseapp.com',
    storageBucket: 'scamreport-62b4c.firebasestorage.app',
    measurementId: 'G-T55TKBFLT6',
  );
}
