import 'dart:developer' as developer;

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

import '../../firebase_options.dart';

// Initialise Firebase. Returns true on success, false if init throws — so the
// rest of the app keeps working when config is incomplete. The typed options
// from firebase_options.dart (generated by `flutterfire configure`) make
// platform mismatches a compile error rather than a runtime "missing
// google_app_id" warning.
Future<bool> initializeFirebase() async {
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e, st) {
    developer.log(
      '[firebase] init skipped — see HOW_TO_CONTRIBUTE.md §3 for config files',
      name: 'firebase',
      error: e,
      stackTrace: st,
    );
    return false;
  }

  // Ask for FCM permission. iOS requires this before getToken() works; on
  // Android the platform grants it implicitly. If the user denies, getToken()
  // returns null and the rest of the app still functions.
  await FirebaseMessaging.instance.requestPermission(
    alert: true,
    badge: true,
    sound: true,
  );

  return true;
}
